---
- name: Configure hosts and deploy application
  hosts: app
  become: yes
  tasks:
    - name: Fetch the latest version of app code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /opt/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /opt/reddit

  handlers:
    - name: reload puma
      become: yes
      systemd: name=puma state=restarted
